name: Go

on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Test
        run: go test -race -covermode=atomic -coverprofile=coverage.out -v `go list ./... | grep -v './example|./cmd'`

      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: Goveralls
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=coverage.out -service=github
